spring:
  application:
    name: notification-service

  # Datasource configuration
  datasource:
    url: jdbc:h2:mem:hedwig
    driverClassName: org.h2.Driver
    username: hedwig
    password: hedwig

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

  # Flyway configuration
  flyway:
    enabled: true
    placeholder-prefix: "$$$"
    # placeholder-suffix: "$$$"

  # Java Mail configuration
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL:SOMEEMAIL}
    password: ${MAIL_PASSWORD:SOMEPASSWORD}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9090
  servlet:
    context-path: /notification-service
