spring:
  application:
    name: notification-service

  # Datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatabase
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:nitesh}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    platform: postgres
    schema: ${DB_SCHEMA_NAME:notification_schema}  # Default schema for JPA
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 100

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA_NAME:notification_schema}

  # Flyway configuration
  flyway:
    enabled: true
    schemas: ${DB_SCHEMA_NAME:notification_schema}  # Schema for Flyway migrations
    placeholder-prefix: "$$${"
    placeholder-suffix: "}$$$"

  # Java Mail configuration
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL:SOMEEMAIL}
    password: ${MAIL_PASSWORD:SOMEPASSWORD}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9090
  servlet:
    context-path: /notification-service
